# Generated by Django 5.1.1 on 2024-10-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_livre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='lien_pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
