# Generated by Django 5.1.1 on 2024-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_livre_lien_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='fichier_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
